spring:
  app:
    current-web-url: http://localhost:8085
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jwt:
    secret: ${JWT_KEY}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
      use_sql_comments: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        formate_sql: true
  mail:
      host: ${EMAIL_HOST}
      port: ${EMAIL_PORT}
      username: ${EMAIL_ID}
      password: ${EMAIL_PASSWORD}
      default-encoding: UTF-8
      properties:
        mail:
          smtp:
            writetimeout: 10000
            connectiontimeout: 10000
            timeout: 10000
            auth: true
            starttls:
              enable: true
              required: true
  logging:
    level:
      root: INFO
      com.roomate.app: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %cyan(%logger{36}) - %msg%n"

server:
  port: ${CONTAINER_PORT:8085}
  error:
    path: /user/error
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        name: jwt
        http-only: true
        secure: true
        path: /



      #    init:
      #      mode: never #says if we should run data files
      #      continue-on-error: false
      #      schema-locations: classpath:/data/schema.sql
      #      data-locations: classpath:/data/data.sql
      #  servlet:
      #    multipart:
      #      enabled: true
      #      max-file-size: 1000MB
      #      max-request-size: 1000MB
      #
      #    verify:
      #      host: ${VERIFY_EMAIL_HOST}

